name: Go

on:
  push

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Get dependencies tools
        run: go get -u golang.org/x/lint/golint

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: code check pretty
        run: make check

      - name: unit test
        run: make test
